-- Neon-ready schema for orchestrator auditing and errors
-- Usage: psql "$DATABASE_URL" -f backend/infra/audit_log.sql

BEGIN;

-- Audit log of general events across agents/phases
CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT NOT NULL,
    agent TEXT NOT NULL,
    phase TEXT,
    payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT audit_log_phase_check CHECK (
        phase IS NULL OR phase IN ('manifest','verify','scaffold','fix')
    )
);

CREATE INDEX IF NOT EXISTS idx_audit_log_job_id ON audit_log(job_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_agent ON audit_log(agent);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at);

-- Orchestrator-surfaced phase validation failures
CREATE TABLE IF NOT EXISTS orchestrator_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT NOT NULL,
    phase TEXT NOT NULL,
    error TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT orchestrator_errors_phase_check CHECK (
        phase IN ('manifest','verify','scaffold','fix')
    )
);

CREATE INDEX IF NOT EXISTS idx_orch_errors_job_id ON orchestrator_errors(job_id);
CREATE INDEX IF NOT EXISTS idx_orch_errors_phase ON orchestrator_errors(phase);
CREATE INDEX IF NOT EXISTS idx_orch_errors_created_at ON orchestrator_errors(created_at);

COMMIT;
